### ISSUE TITLE
how to make responsive twitter embed to mobile device? its available on options ?

### ISSUE THREAD

**Issue by qipoy** [raae/gatsby-remark-oembed#85]

**Comment by anonimoconiglio** [comment]
you can try `gatsby-remark-responsive-iframe`, it worked for me very well, although it generates some problems with my old posts (they have plenty of html code inside md files so there was some conflicts I didn't have the time to check).

an alternative - that's the one I'm using right now - is to insert a global css media query: 

```css
@media (max-width: 550px) {
	.twitter-tweet {max-width: 300px !important;}
	iframe { width: 300px; }
}
```

It is not elegant but it works well...
