### ISSUE TITLE
Center instagram oembed

### ISSUE THREAD

**Issue by iturpablo** [raae/gatsby-remark-oembed#86]
Hi Raae,

 how can I center and embedded an Instagram post, it is always on the left and would love to center it. 

Cheers 🍻
Pablo

**Comment by 2color** [comment]
I had a similar problem. 

I resolved it by overriding the inline CSS `margin: 1px` that the blockquote gets.

I added the following in a separate css file to resolve this:

```css
blockquote.instagram-media {
  margin: auto !important;
}
```
